### ISSUE TITLE
Is idle-backoff-ms still a thing?

### ISSUE THREAD

**Issue by enragedginger** [onyx-platform/onyx-amazon-sqs#6]
The input task example in the readme has an entry for `:sqs/idle-backoff-ms idle-backoff-ms`. However, the schema defined for the input task will not allow it. Therefore, we should either remove this example entry from the docs, or update the schema to allow this entry.

Thoughts?

**Comment by lbradstreet** [comment]
Removed from the docs.  Thanks for the report!
